DATA:
  IMG_SIZE: 256
MODEL:
  TYPE: swinv2
  NAME: swinv2_base_patch4_window8_256
  DROP_PATH_RATE: 0.2
  LABEL_SMOOTHING: 0.1
  NUM_CLASSES: 15
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 8
AMP_ENABLE: False
TRAIN:
  AUTO_RESUME: false
  EPOCHS: 70
  ACCUMULATION_STEPS: 1
  BASE_LR: 5e-04
  WARMUP_EPOCHS: 10
  WARMUP_LR: 5e-06               # 调整后的 warmup lr
  MIN_LR: 1e-07
  WEIGHT_DECAY: 1e-5             # 注意：这个值较小，如训练时发现过拟合可适当提高（例如1e-4）
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 40        # 在第40 epoch时突变式下降
    DECAY_RATE: 0.1         # 降低为原来的十分之一
    WARMUP_PREFIX: true     # 先执行warmup，再进入step

AUG:
  AUTO_AUGMENT: rand-m5-mstd0.2-n2    # ✅ 更温和的 RandAugment，只做 1 种轻增强，强度减弱
  COLOR_JITTER: 0.2                  # ✅ 色彩扰动更低，仅轻微变化
  CUTMIX: 0.0
  CUTMIX_MINMAX: null
  MIXUP: 0.0
  MIXUP_MODE: 'batch'
  MIXUP_PROB: 0.0
  MIXUP_SWITCH_PROB: 0.0
  REPROB: 0.1                        # ✅ 减低随机擦除的触发概率为 10%
  REMODE: 'pixel'
  RECOUNT: 1
  RANDOM_OCCLUSION:
    ENABLE: true
    NUM_BLOCKS: 1
    BLOCK_SIZE: 24                  # ✅ 缩小遮挡块，避免遮住大目标
    PROB: 0.2                       # ✅ 遮挡概率从 0.3 降到 0.1