DATA:
  IMG_SIZE: 256
MODEL:
  TYPE: swinv2
  NAME: swinv2_base_patch4_window8_256
  DROP_PATH_RATE: 0.2
  LABEL_SMOOTHING: 0.1
  NUM_CLASSES: 15
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 8
AMP_ENABLE: False
TRAIN:
  AUTO_RESUME: false
  EPOCHS: 70
  ACCUMULATION_STEPS: 1
  BASE_LR: 5e-04
  WARMUP_EPOCHS: 10
  WARMUP_LR: 5e-06
  MIN_LR: 1e-07
  WEIGHT_DECAY: 1e-5
  LR_SCHEDULER:
    NAME: cosine
    DECAY_EPOCHS: 100
    DECAY_RATE: 0.1
    WARMUP_PREFIX: true
AUG:
  AUTO_AUGMENT: rand-m5-mstd0.2-n2
  COLOR_JITTER: 0.0
  CUTMIX: 0.0
  CUTMIX_MINMAX: null
  MIXUP: 0.0
  MIXUP_MODE: batch
  MIXUP_PROB: 0.0
  MIXUP_SWITCH_PROB: 0.0
  REPROB: 0.0
  REMODE: pixel
  RECOUNT: 0
  RANDOM_OCCLUSION:
    ENABLE: False
    NUM_BLOCKS: 1
    BLOCK_SIZE: 32
    PROB: 0.3
